schema: ./apps/timesheet2-api/src/schema.graphql
documents: ./apps/timesheet2-app/src/api/operation.graphql
generates:
    ./apps/timesheet2-app/src/api/graphql.ts:
        plugins:
            - "typescript"
            - "typescript-operations"
            - "typescript-react-apollo"
    ./graphql.schema.json:
        plugins:
            - "introspection"
