schema: ./apps/nexttimesheet/graphql/schema.graphql
documents: ./apps/nexttimesheet/graphql/operation.graphql
generates:
    ./apps/nexttimesheet/lib/graphql.ts:
        plugins:
            - "typescript"
            - "typescript-operations"
            - "typescript-react-apollo"
    ./graphql.schema.json:
        plugins:
            - "introspection"
