// By convention, actions that end in "_SUCCESS" are assumed to have been the result of a completed
// API call. But since we're doing an optimistic delete, we're hiding loading state.
// So this action name deliberately omits the "_SUCCESS" suffix.
// If it had one, our apiCallsInProgress counter would be decremented below zero
// because we're not incrementing the number of apiCallInProgress when the delete request begins.

//timesheet
export const READ_TIMESHEET_SUCCESS = "READ_TIMESHEET_SUCCESS";
export const CREATE_TIMESHEET_SUBMISSION_SUCCESS =
    "CREATE_TIMESHEET_SUBMISSION_SUCCESS";
export const SORT_TIMESHEET = "SORT_TIMESHEET";

// templates
export const READ_TEMPLATES_SUCCESS = "READ_TEMPLATES_SUCCESS";
export const READ_TEMPLATE_SUCCESS = "READ_TEMPLATE_SUCCESS";
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS";
export const CREATE_TEMPLATE_SUCCESS = "CREATE_TEMPLATE_SUCCESS";
export const UPDATE_TEMPLATE_SUCCESS = "UPDATE_TEMPLATE_SUCCESS";

//time entries
export const SAVE_TIME_ENTRY_SUCCESS = "SAVE_TIME_ENTRY_SUCCESS";
export const SAVE_TIME_ENTRY_ROW_SUCCESS = "SAVE_TIME_ENTRY_ROW_SUCCESS";
export const SAVE_TIME_ENTRY_ROW_OFFLINE = "SAVE_TIME_ENTRY_ROW_OFFLINE";
export const DELETE_TIME_ENTRY_SUCCESS = "DELETE_TIME_ENTRY_SUCCESS";
export const DELETE_TIME_ENTRY_ROW_SUCCESS = "DELETE_TIME_ENTRY_ROW_SUCCESS";
export const CREATE_TIME_ENTRY_ROW = "CREATE_TIME_ENTRY_ROW";
export const SAVE_ALTERNATE_ENTRY_SUCCESS = "SAVE_ALTERNATE_ENTRY_SUCCESS";
export const DELETE_ALTERNATE_ENTRY_SUCCESS = "DELETE_ALTERNATE_ENTRY_SUCCESS";
export const DELETE_UNUSEDROWS_SUCCESS = "DELETE_UNUSED_ROWS_SUCCESS";
//Day comments
export const SAVE_TIME_SHEET_DAY_COMMENT_SUCCESS =
    "SAVE_TIME_SHEET_COMMENT_SUCCESS";
export const DELETE_TIME_SHEET_DAY_COMMENT_SUCCESS =
    "DELETE_TIME_SHEET_COMMENT_SUCCESS";

//Objects & Employee
export const READ_OBJECTS_SUCCESS = "READ_OBJECTS_SUCCESS";
export const SAVE_PROJECT_SUCCESS = "SAVE_PROJECT_SUCCESS";
export const SAVE_WORK_CODE_SUCCESS = "SAVE_WORK_CODE_SUCCESS";
export const SAVE_DEPARTMENT_SUCCESS = "SAVE_DEPARTMENT_SUCCESS";
export const SAVE_SETTINGS_SUCCESS = "SAVE_SETTINGS_SUCCESS";
export const SAVE_EMPLOYEE_SUCCESS = "SAVE_EMPLOYEE_SUCCESS";
export const READ_EMPLOYEES_SUCCESS = "READ_EMPLOYEES_SUCCESS";
export const READ_EMPLOYEE_WORK_CODE_SUCCESS =
    "READ_EMPLOYEE_WORK_CODE_SUCCESS";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_EMPLOYEE_PREFS_SUCCESS = "SAVE_EMPLOYEE_PREFS_SUCCESS";
export const CREATE_EMPLOYEE_PINNED_ROW_SUCCESS =
    "CREATE_EMPLOYEE_PINNED_ROW_SUCCESS";
export const DELETE_EMPLOYEE_PINNED_ROW_SUCCESS =
    "DELETE_EMPLOYEE_PINNED_ROW_SUCCESS";

//User
export const READ_CURRENT_USER_SUCCESS = "READ_CURRENT_USER_SUCCESS";
export const LOAD_USER_WORK_CODES_SUCCESS = "LOAD_USER_WORK_CODES_SUCCESS";
export const SAVE_CURRENT_USER_PASSWORD_SUCCESS =
    "SAVE_CURRENT_USER_PASSWORD_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//Reports
export const READ_DYNAMICS_REPORT_SUCCESS = "READ_DYNAMICS_REPORT_SUCCESS";
export const READ_EMPLOYEE_TIME_SHEET_REPORT_SUCCESS =
    "READ_EMPLOYEE_TIME_SHEET_REPORT_SUCCESS";
export const READ_TARDY_EMPLOYEES_REPORT_SUCCESS =
    "READ_TARDY_EMPLOYEES_REPORT_SUCCESS";

//API
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const BEGIN_TIME_ENTRY_LOAD = "BEGIN_TIME_ENTRY_LOAD";
export const TIME_ENTRY_LOAD_ERROR = "TIME_ENTRY_LOAD_ERROR";

//Manager
export const READ_SUBORDINATES_SUCCESS = "READ_SUBORDINATES_SUCCESS";
export const READ_SUBORDINATES_WORK_CODES_SUCCESS =
    "READ_SUBORDINATES_WORK_CODES_SUCCESS";
export const DELETE_TIMESHEET_LOCK_SUCCESS = "DELETE_TIMESHEET_LOCK_SUCCESS";
export const CREATE_TIMESHEET_LOCK_SUCCESS = "CREATE_TIMESHEET_LOCK_SUCCESS";
export const SAVE_SUBORDINATE_ROWS = "SAVE_SUBORDINATE_ROWS";

//approval
export const UPDATE_PAYROLL_APPROVAL_SUCCESS =
    "UPDATE_PAYROLL_APPROVAL_SUCCESS";
export const UPDATE_SUPERVISOR_APPROVAL_SUCCESS =
    "uPDATE_SUPERVISOR_APPROVAL_SUCCESS";

//LOGIN
export const AAD_LOGIN_SUCCESS = "AAD_LOGIN_SUCCESS";
export const AAD_LOGOUT_SUCCESS = "AAD_LOGOUT_SUCCESS";

//client settings
export const LOAD_SIDEBAR_PIN_TOGGLE = "LOAD_SIDEBAR_PIN_TOGGLE";
export const SET_SIDEBAR_PIN_TOGGLE = "SET_SIDEBAR_PIN_TOGGLE";
export const LOAD_EXPECTED_HOURS = "LOAD_EXPECTED_HOURS";
export const SET_EXPECTED_HOURS = "SET_EXPECTED_HOURS";
export const LOAD_CHECK_EXPECTED_HOURS = "LOAD_CHECK_EXPECTED_HOURS";
export const SET_CHECK_EXPECTED_HOURS = "SET_CHECK_EXPECTED_HOURS";
export const LOAD_PINNED_ROWS = "LOAD_PINNED_ROWS";
export const SET_PINNED_ROWS = "SET_PINNED_ROWS";
